sudo: false
language: java
jdk:
  - oraclejdk8

before_install:
  - wget https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip
  - unzip protoc-3.7.1-linux-x86_64.zip
  - export PROTOC_COMPILER="$(pwd)/protoc"

os:
  - linux

script: ./gradlew clean build

